#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "apsaK WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-keygen ./build/docs/apsak-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "apsaK WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-rpc ./build/docs/apsak-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "apsaK WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-core ./build/docs/apsak-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "apsaK WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak ./build/docs/apsak.ts
else
    echo "building keygen"
    typedoc --name "apsaK WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-keygen ./build/docs/apsak-keygen.ts
    echo "building rpc"
    typedoc --name "apsaK WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-rpc ./build/docs/apsak-rpc.ts
    echo "building core"
    typedoc --name "apsaK WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak-core ./build/docs/apsak-core.ts
    echo "building full"
    typedoc --name "apsaK WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/apsak ./build/docs/apsak.ts

fi