#!/bin/bash
# This script builds the Rusty apsaK WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/apsak-wasm32-sdk/web
mkdir -p release/apsak-wasm32-sdk/nodejs
mkdir -p release/apsak-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name apsak-rpc --out-dir web/apsak-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name apsak --out-dir web/apsak-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name apsak --out-dir web/apsak-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name apsak --out-dir web/apsak-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name apsak --out-dir web/apsak-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name apsak --out-dir web/apsak-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name apsak --out-dir web/apsak-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name apsak --out-dir web/apsak --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name apsak --out-dir web/apsak-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name apsak --out-dir nodejs/apsak --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name apsak --out-dir nodejs/apsak-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name apsak --out-dir build/docs/apsak --features wasm32-sdk $@
typedoc --name "apsaK WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/apsak-keygen ./build/docs/apsak-keygen.ts
typedoc --name "apsaK WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/apsak-rpc ./build/docs/apsak-rpc.ts
typedoc --name "apsaK WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/apsak-core ./build/docs/apsak-core.ts
typedoc --name "apsaK WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/apsak ./build/docs/apsak.ts

# cp -r ../rpc/wrpc/wasm/web/apsak-rpc release/apsak-wasm32-sdk/web/apsak-rpc
cp -r web/apsak-keygen release/apsak-wasm32-sdk/web/apsak-keygen
cp -r web/apsak-keygen-dev release/apsak-wasm32-sdk/web/apsak-keygen-dev

cp -r web/apsak-rpc release/apsak-wasm32-sdk/web/apsak-rpc
cp -r web/apsak-rpc-dev release/apsak-wasm32-sdk/web/apsak-rpc-dev

cp -r web/apsak-core release/apsak-wasm32-sdk/web/apsak-core
cp -r web/apsak-core-dev release/apsak-wasm32-sdk/web/apsak-core-dev

cp -r web/apsak release/apsak-wasm32-sdk/web/apsak
cp -r web/apsak-dev release/apsak-wasm32-sdk/web/apsak-dev

cp -r nodejs/apsak release/apsak-wasm32-sdk/nodejs/apsak
cp -r nodejs/apsak-dev release/apsak-wasm32-sdk/nodejs/apsak-dev

cp -r docs/apsak-keygen release/apsak-wasm32-sdk/docs/apsak-keygen
cp -r docs/apsak-rpc release/apsak-wasm32-sdk/docs/apsak-rpc
cp -r docs/apsak-core release/apsak-wasm32-sdk/docs/apsak-core
cp -r docs/apsak release/apsak-wasm32-sdk/docs/apsak

mkdir -p release/apsak-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/apsak-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/apsak-wasm32-sdk/examples/
cp -r examples/web release/apsak-wasm32-sdk/examples/
cp -r examples/init.js release/apsak-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/apsak-wasm32-sdk/examples/
cp -r examples/package.json release/apsak-wasm32-sdk/examples/

pushd .
cd release/apsak-wasm32-sdk/examples
npm install
popd

# tsc release/apsak-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/apsak-wasm32-sdk/index.html
cp README.md release/apsak-wasm32-sdk/README.md
cp CHANGELOG.md release/apsak-wasm32-sdk/CHANGELOG.md
cp LICENSE release/apsak-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/apsak-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r apsak-wasm32-sdk.zip apsak-wasm32-sdk
popd
