[[resolver]]
url = "https://ng1.apsak.org"
enable = false

[[resolver]]
url = "https://ng2.apsak.org"
enable = false

[[resolver]]
url = "https://ng3.apsak.org"
enable = false

[[resolver]]
url = "https://ng4.apsak.org"
enable = true
