[package]
name = "apsak-pow"
description = "apsaK proof-of-work"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = []

[dependencies]
js-sys.workspace = true
apsak-consensus-core.workspace = true
apsak-consensus-client.workspace = true
apsak-hashes.workspace = true
apsak-math.workspace = true
apsak-utils.workspace = true
wasm-bindgen.workspace = true
workflow-wasm.workspace = true
num.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench"
harness = false